### PR TITLE
Nft picker

### PR DESCRIPTION
**Pull request by RajGM**
NFT-Picker component completed as per design.
Dummy data is been added as well.
Need to merge this into main and then use the real data passed from NFT request. 
Issue: #6

### CODE REVIEW

**Comment by Tess99854** [comment]
@RajGM Great work but I think it's missing some design details such as: 
- the title "Your NFTs"
- centering the div and adding a border-radius 
- making the border thinner and lowering its opacity
- giving the NFTs holders less width 
- the "picked" class for when an NFT is picked 
And lastly, in case the NFTs number overflows the container the user should be able to swap left and right in a carousel-like manner, you can check this component https://daisyui.com/components/carousel/#slide4

**Comment by RajGM** [comment]
Got it.

**Comment by RajGM** [comment]
Hi @Tess99854 
The swap feature is present already.

**Comment by abdelhakeem** [comment]
There are some failing checks.
Also, I think this component would ideally take an array of `Nft` objects as a prop and display the picker accordingly. You will also need to keep track of the currently selected NFT, possibly in the parent component/page since it has to be shared across other components (NFT selection section and NFT editor).

**Comment by RajGM** [comment]
@abdelhakeem 
I think we need to roll back this the merge and then look at the failing test.

**Comment by Tess99854** [comment]
@RajGM it's reverted you can work on this now

**Comment by RajGM** [comment]
On it.

**Pull request merged**
