### PR TITLE
Add useMetaplex hook

### LINKED ISSUE #23: Add useMetaplex hook
Add a `useMetaplex` hook in `hooks/useMetaplex.ts` that uses the wallet adapter and its connection to create a Metaplex object that we can use uniformly across all functions that use Metaplex's SDK (example: https://github.com/abdelhakeem/nft-mutation-demo/blob/main/hooks/useMetaplex.ts)

### PR DESCRIPTION
**Pull request by abdelhakeem**
Resolves #23

### CODE REVIEW

**Review by Tess99854 — APPROVED** [review]

**Comment by Tess99854** [comment]
@abdelhakeem should we initialize the connection with the cluster that the user picked in the selector instead of the wallet's cluster? 
sorry for not saying this earlier, I just tested it and the first option seemed much more convenient

**Comment by abdelhakeem** [comment]
> @abdelhakeem should we initialize the connection with the cluster that the user picked in the selector instead of the wallet's cluster? sorry for not saying this earlier, I just tested it and the first option seemed much more convenient

Yeah, we should use the selected cluster in the cluster picker, because actually we do not have access to the cluster selected in the wallet extension.

**Comment by Tess99854** [comment]
> > @abdelhakeem should we initialize the connection with the cluster that the user picked in the selector instead of the wallet's cluster? sorry for not saying this earlier, I just tested it and the first option seemed much more convenient
> 
> Yeah, we should use the selected cluster in the cluster picker, because actually we do not have access to the cluster selected in the wallet extension.

yes what I meant is using 
```
 const connection = new Connection(clusterApiUrl(useAppSelector(selectCluster))) 
```
instead of `useConnection`

**Comment by abdelhakeem** [comment]
> > > @abdelhakeem should we initialize the connection with the cluster that the user picked in the selector instead of the wallet's cluster? sorry for not saying this earlier, I just tested it and the first option seemed much more convenient
> > 
> > 
> > Yeah, we should use the selected cluster in the cluster picker, because actually we do not have access to the cluster selected in the wallet extension.
> 
> yes what I meant is using
> 
> ```
>  const connection = new Connection(clusterApiUrl(useAppSelector(selectCluster))) 
> ```
> 
> instead of `useConnection`

Oh, I thought you meant in the wallet context provider:

https://github.com/abdelhakeem/nft-mutator/blob/7e842d541a60597c63d09015d65f8fcdce2e692a/components/layout/walletContextProvider.tsx#L17-L18

This way, the `useConneection` hook will use the user selected cluster.

**Pull request merged**
