### PR TITLE
Implemented `Landing` page

### LINKED ISSUE #1: Implement first page design

### PR DESCRIPTION
**Pull request by NikhilSharma03**
## Description

- This PR resolves #1 

### Big Screen
Screenshot 2022-07-29 204322

### Mobile
Screenshot 2022-07-29 204415

### CODE REVIEW

**Comment by NikhilSharma03** [comment]
@abdelhakeem Do we want the same behavior for `Get Started` button as in hydra wallet UI. (i.e. Connect wallet, and if wallet connected then navigate to all NFT's Page)

**Comment by abdelhakeem** [comment]
> @abdelhakeem Do we want the same behavior for `Get Started` button as in hydra wallet UI. (i.e. Connect wallet, and if wallet connected then navigate to all NFT's Page)

Yes, I think this would be sane behavior.

**Comment by NikhilSharma03** [comment]
Done!

**Comment by abdelhakeem** [comment]
This is awesome work! Make sure to rebase on `main` since #15 is now merged. Let's see what @rishabh-vasudevan thinks about the design.

**Review by abdelhakeem — APPROVED** [review]

**Comment by Tess99854** [comment]
@NikhilSharma03 This is looking good, maybe we can add some glow to the `Get started` button when we hover on it, I think we should rebase and merge after that

**Comment by NikhilSharma03** [comment]
Done @Tess99854

**Comment by Tess99854** [comment]
@NikhilSharma03 can you rebase to fix the conflicts

**Comment by NikhilSharma03** [comment]
I think we are good to merge here now.

**Review by abdelhakeem — APPROVED** [review]

**Pull request merged**
