### PR TITLE
Hero section

### PR DESCRIPTION
**Pull request by haianhltr**

### CODE REVIEW

**Comment by haianhltr** [comment]
The test fail because of these 2 files: 
`nft-mutator/components/NFT_picker.ts`
`nft-mutator/components/NFT.tsx`

**Comment by abdelhakeem** [comment]
Isn't this a duplicate of #13?

**Comment by haianhltr** [comment]
It is just a base for the landing page I made like 6 days ago. If there is conflicts, do you want me to reset the commit ?

**Comment by abdelhakeem** [comment]
> It is just a base for the landing page I made like 6 days ago. If there is conflicts, do you want me to reset the commit ?

I think you can coordinate the work on the landing page in #13 with @NikhilSharma03. I will revert this merge since we already have an open PR for the landing page.

**Pull request merged**
