### PR TITLE
Nft selection

### PR DESCRIPTION
**Pull request by RajGM**
This PR adds the component for NFT-selection

### CODE REVIEW

**Comment by RajGM** [comment]
Issue #7

**Comment by Tess99854** [comment]
@RajGM after fixing the conflicts this should be ready for merge

**Comment by RajGM** [comment]
ok @Tess99854

**Comment by abdelhakeem** [comment]
I think you need to remove package-lock.json and resolve the conflicts in yarn.lock.

**Comment by Tess99854** [comment]
@abdelhakeem should be good to go now

**Review by abdelhakeem — APPROVED** [review]

**Pull request merged**
